### ISSUE TITLE
facing error in eosio postgras 

### ISSUE THREAD

**Issue by awaissakhi11** [EOSIO/eosio-explorer#166]
im not able to connect with with postgras nodeos is working find but progress with show me red not green 
![image_2021-05-24_08-58-15](https://user-images.githubusercontent.com/38858086/119337644-2535bc80-bca0-11eb-941c-f1ea8f46f525.png)

**Comment by jeanrobatto** [comment]
Same here! Would love to have a solution to this.

**Comment by temtomk** [comment]
Me too.
I have same problem.

**Comment by James-Mart** [comment]
Same error here.

Callstack in pm2 logs:

> 1|eosio explorer  | Error executing get blocks query::  error: relation "chain.block_info" does not exist
1|eosio explorer  |     at Connection.parseE (/Users/james/.config/yarn/global/node_modules/pg/lib/connection.js:604:13)
1|eosio explorer  |     at Connection.parseMessage (/Users/james/.config/yarn/global/node_modules/pg/lib/connection.js:403:19)
1|eosio explorer  |     at Socket.<anonymous> (/Users/james/.config/yarn/global/node_modules/pg/lib/connection.js:123:22)
1|eosio explorer  |     at Socket.emit (events.js:311:20)
1|eosio explorer  |     at addChunk (_stream_readable.js:294:12)
1|eosio explorer  |     at readableAddChunk (_stream_readable.js:275:11)
1|eosio explorer  |     at Socket.Readable.push (_stream_readable.js:209:10)
1|eosio explorer  |     at TCP.onStreamRead (internal/stream_base_commons.js:186:23)

**Comment by oraki23** [comment]
Same error here, in the pg-fill container, im getting:

> starting postgres
> info  2022-04-19T03:59:10.644 fill-pg   main.cpp:98                   main                 ] fill-pg version v0.2.0-alpha-21-g7d6ada9-dirty
> info  2022-04-19T03:59:10.644 fill-pg   main.cpp:99                   main                 ] fill-pg using configuration file /root/.local/share/eosio/fill-pg/config/config.ini
> info  2022-04-19T03:59:10.644 fill-pg   main.cpp:100                  main                 ] fill-pg data directory is /root/.local/share/eosio/fill-pg/data
> info  2022-04-19T03:59:10.646 fill-pg   fill_pg_plugin.cpp:97         fpg_session          ] connect to postgresql
> info  2022-04-19T03:59:10.810 fill-pg   fill_pg_plugin.cpp:218        create_tables        ] create schema "chain"
> error 2022-04-19T03:59:12.927 fill-pg   state_history_connecti:157    catch_and_close      ] bad variant index
> info  2022-04-19T03:59:12.927 fill-pg   state_history_connecti:182    close                ] closing state-history socket
